### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by rtingchaleun**

### CODE REVIEW

**Comment by samgaco** [comment]
### Hi, @rtingchaleun and @Oitur :vulcan_salute: 

### Good work so far, some things to address before proceeding:

* In the navbar there should be some elements (the content doesn't matter), as in the original website, and they should be positioned with either floats or display flex

* You should make usage of semantic elements through the project, read more about them [here](https://www.w3schools.com/html/html5_semantic_elements.asp).

* The articles should use the `<article>` tag.

* Are you working collaboratively? I see only one commit by @Oitur , he should be the one doing the next commits.

### Please, address these issues and submit back for another code review when you are done :+1:

**Comment by samgaco** [comment]
### Hi again @rtingchaleun and @Oitur :hand: 

### The project looks perfect :+1:  but there are some issues that we have to go through before we can give you the approval.

#### Please, you should address this point before proceeding.

> * Are you working collaboratively? I see only one commit by @Oitur , he should be the one doing the next commits.

And also you should make use of **semantic elements.**

* Use the `<main> ` for the dominant content of the body of your project
* Use the `<footer>` tag for the footer

More information about it [here](https://www.w3schools.com/html/html5_semantic_elements.asp).



### Regards!

**Comment by Oitur** [comment]
Hi @samgaco 
Yes, we're working collaboratively, we change drivers every 1.5 hours or so and discuss every line we write.

**Comment by samgaco** [comment]
### Hi @Oitur and @rtingchaleun :hand: 

### Thanks for addressing these issues. Your project is approved :+1:  You can merge to the master branch and submit the project completion form. :clap: Regards! :muscle:

**Pull request merged**
